In [1]:
import pandas as pd
import warnings
import numpy as np
from sklearn import neighbors
from sklearn import datasets
from sklearn import metrics
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv("sensor_raw.csv")
data

Target(Class)     GyroX     GyroY     GyroZ      AccX      AccY  \
0                 1 -0.923664  3.694656  0.824427  0.162598 -0.086670   
1                 1 -0.908397  4.534351  0.832061  0.175781 -0.100586   
2                 1  0.786260  3.969466  0.587786  0.322754 -0.140381   
3                 1  0.335878  4.564885 -0.251908  0.480225 -0.226807   
4                 1  3.351145  2.694656 -0.106870  0.426025 -0.253906   
...             ...       ...       ...       ...       ...       ...   
1109              4 -1.961832  2.358779  8.893130  0.472900 -0.431152   
1110              4 -0.435115  5.396947  1.282443  0.459961 -0.227051   
1111              4 -1.061069  4.534351  1.183206  0.419189 -0.192871   
1112              4 -1.015267  5.259542  0.656489  0.308838 -0.090088   
1113              4 -0.877863  4.488550  0.045802  0.098145 -0.015869   

          AccZ  
0    -0.969482  
1    -1.013184  
2    -0.911621  
3    -0.936768  
4    -0.950195  
...        ...  
1109 -0.873535  
1110 -0.967041  
1111 -1.002686  
1112 -1.023193  
1113 -1.001221  

[1114 rows x 7 columns]

In [3]:
x=data.to_numpy()

In [4]:
yd=data['Target(Class)']
y=yd.to_numpy()
knn=neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(x,y)
yhat=knn.predict(x)
print(yhat)
print('Predicted value: ',yhat[-1])
print('Real Target: ',y[-1])
print(knn.score(x,y))

[1 1 1 ... 4 4 4]
Predicted value:  4
Real Target:  4
0.9138240574506283


In [5]:
np.unique(data['Target(Class)'])

array([1, 2, 3, 4], dtype=int64)

In [6]:
yhat=knn.predict(x)
TP=np.sum(np.logical_and(yhat==-1,y==-1))
FP=np.sum(np.logical_and(yhat==-1,y==1))
TN=np.sum(np.logical_and(yhat==1,y==1))
FN=np.sum(np.logical_and(yhat==1,y==-1))
print('TP: ',TP,', FP: ',FP)
print('FN: ',FN,', TN: ',TN)
print(metrics.confusion_matrix(yhat , y))

TP:  0 , FP:  0
FN:  0 , TN:  231
[[231  20   8   0]
 [ 18 256  17   0]
 [  3  12 318  11]
 [  0   0   7 213]]


In [7]:
knn=neighbors.KNeighborsClassifier(n_neighbors=10)
knn.fit(x,y)
yhat=knn.predict(x)
print("Classification accuracy:",metrics.accuracy_score(yhat , y))
print("Confusion matrix: \n",metrics.confusion_matrix(yhat , y))

Classification accuracy: 0.8913824057450629
Confusion matrix: 
 [[226  24   6   1]
 [ 23 247  23   1]
 [  3  16 313  15]
 [  0   1   8 207]]


In [8]:
c=np.random.permutation(y.size)
d=0.3
e=int(np.ceil(y.shape[0]*d))
x_train = x[c[:e].ravel(),:]
y_train = y[c[:e].ravel()]
x_test=x[c[e:].ravel(),:]
y_test=y[c[e:].ravel()]
print('Traing shape:',(x_train.shape,y_train.shape[-1]))
print('Testing shape:',(x_test.shape,y_test.shape[-1]))

Traing shape: ((335, 7), 335)
Testing shape: ((779, 7), 779)


In [9]:
knn=neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
yhat=knn.predict(x_train)
print('Training Stats:\n')
print('Classification Accuracy=',metrics.accuracy_score(yhat,y_train),'\n')
print('Confusion Matrix:\n',metrics.confusion_matrix(y_train,yhat)[0],'\n',metrics.confusion_matrix(y_train,yhat)[1])

Training Stats:

Classification Accuracy= 0.8955223880597015 

Confusion Matrix:
 [69  6  2  0] 
 [ 6 81  4  0]


In [10]:
knn=neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(x_test,y_test)
yhat=knn.predict(x_test)
print('Testing Stats:\n')
print('Classification Accuracy=',metrics.accuracy_score(yhat,y_test),'\n')
print('Confusion Matrix:\n',metrics.confusion_matrix(y_test,yhat)[0],'\n',metrics.confusion_matrix(y_test,yhat)[1])

Testing Stats:

Classification Accuracy= 0.9075738125802311 

Confusion Matrix:
 [159  16   0   0] 
 [ 18 172   7   0]


In [11]:
from sklearn.model_selection import train_test_split
h=0.3
g=np.zeros ((10 ,))
for i in range (10):
    x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=h,random_state=1)
    knn = neighbors.KNeighborsClassifier(n_neighbors=5)
    knn.fit(x_train , y_train)
    yhat = knn.predict(x_test)
g[i] = metrics.accuracy_score(yhat , y_test)
g.shape = (1, 10)
print("Mean expected error:",str(np.mean(g[0])))

Mean expected error: 0.08537313432835822


In [12]:
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

           1       0.84      0.89      0.87        83
           2       0.79      0.75      0.77        79
           3       0.85      0.88      0.86       109
           4       0.97      0.89      0.93        64

    accuracy                           0.85       335
   macro avg       0.86      0.85      0.86       335
weighted avg       0.85      0.85      0.85       335

